import scrapy


class JobItem(scrapy.Item):
    platform = scrapy.Field()
    title = scrapy.Field()
    company_name = scrapy.Field()
    company_logo = scrapy.Field()
    company_website = scrapy.Field()
    company_description = scrapy.Field()
    location = scrapy.Field()
    city = scrapy.Field()
    province = scrapy.Field()
    country = scrapy.Field()
    description = scrapy.Field()
    salary_min = scrapy.Field()
    salary_max = scrapy.Field()
    salary_currency = scrapy.Field()
    salary_period = scrapy.Field()
    job_type = scrapy.Field()
    employment_type = scrapy.Field()
    work_type = scrapy.Field()
    experience_level = scrapy.Field()
    category = scrapy.Field()
    subcategory = scrapy.Field()
    skills = scrapy.Field()
    tags = scrapy.Field()
    benefits = scrapy.Field()
    education = scrapy.Field()
    source_url = scrapy.Field()
    apply_url = scrapy.Field()
    posting_date = scrapy.Field()
    expired_date = scrapy.Field()
    updated_at = scrapy.Field()
    scraped_at = scrapy.Field()
    is_active = scrapy.Field()
    is_internship = scrapy.Field()
